spring:
  datasource:
    url: jdbc:h2:file:/opt/data/ad-analysis/db/ad-analysis
    username: kiona
    password: kiona
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    view:
      suffix: ".html"

server:
  port: 8888
