spring:
  datasource:
    url: jdbc:h2:file:/opt/data/ad-analysis/db/ad-analysis
    username: kiona
    password: kiona
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /data-console
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    view:
      suffix: ".html"

server:
  port: 8888
